version: 0.2
env:
  variables:
    APP_NAME: "personal-notes-asf"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo install process started
      - npm install && npm install --save-dev @angular/cli@12.2.14
  build:
    commands:
      - echo build process started now
      - ng build
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist
      - ls -la
      - aws s3 sync . s3://asfpersonblog-hmg --delete